
//The file structure
//openworld_alpha/                      # orginal name
//├── CMakeLists.txt                    # Build configuration
//├── main.cpp                          # Program entry, window, main loop, orchestration
//│
//├── core/                             # Engine‑level reusable components
//│   ├── AABBHelpers.hpp               # Shared AABB overlap & correction functions
//│   ├── Mesh.hpp / Mesh.cpp           # VAO/VBO wrapper, draw calls, move semantics
//│   ├── Shader.hpp / Shader.cpp       # Shader loading, compiling, uniform setting
//│   ├── FirstPersonCamera.hpp / .cpp  # Player camera, movement, sprint, FOV
//│   ├── Frustum.hpp / Frustum.cpp     # Frustum culling for rendering optimisation
//│   ├── FPSCounter.hpp / FPSCounter.cpp # FPS measurement (used in window title)
//│   ├── ResourceManager.hpp / .cpp    # Placeholder for future asset management
//│   ├── TextRenderer.hpp / TextRenderer.cpp # On‑screen text (currently non‑functional)
//│   ├── Version.hpp                   # Version and release stage macros
//│   │
//│   ├── physics/                      # Physics subsystem
//│   │   ├── RigidBody.hpp / .cpp      # Position, velocity, mass, halfExtents, forces
//│   │   ├── Collider.hpp / .cpp       # AABB and Sphere colliders (AABB used everywhere)
//│   │   └── PhysicsWorld.hpp / .cpp   # Gravity, collision resolution, kinematic support
//│   │
//│   └── core/                         # Third‑party single‑header libs
//│       └── stb_easy_font.h           # Bitmap font rendering (used by TextRenderer)
//│
//├── objects/                          # Game‑specific object logic
//│   ├── GameObject.hpp / .cpp         # Base class for all interactive objects
//│   ├── Player.hpp / .cpp             # Player specific (RigidBody + height)
//│   ├── Cube.hpp / .cpp               # Cube mesh generator (LOD variants)
//│   ├── Plane.hpp / .cpp              # Ground plane mesh
//│   ├── wall.hpp / wall.cpp           # Wall mesh (box with custom dimensions)
//│   └── ObjectFactory.hpp / .cpp      # World building: creates all objects (cubes, walls, triggers, etc.)
//│
//├── assets/                           # Raw data files (copied to build dir)
//│   ├── models/                       # (empty – reserved for .obj/.gltf files)
//│   ├── textures/                     # (empty – reserved for images)
//│   └── shaders/
//│       ├── basic.vert                # Simple vertex shader (uses objectColor uniform)
//│       ├── basic.frag                # Simple fragment shader
//│       ├── outline/                  # Outline effect shaders (barycentric edge detection)
//│       │   ├── outline.vert
//│       │   ├── outline.geom
//│       │   └── outline.frag
//│       └── text/                     # 2D text shaders (for TextRenderer)
//│           ├── text.vert
//│           └── text.frag
//│
//├── glad/                             # OpenGL loader (generated by GLAD)
//│   ├── include/
//│   │   ├── KHR/
//│   │   └── glad/
//│   └── src/
//│       └── glad.c
//│
//└── build/                            # CMake output (not shown in source control)
// main.cpp

// 1 unit = 1 meter

// For GLFW Keys: https://github.com/glfw/glfw/blob/master/include/GLFW/glfw3.h

#include <cstring>
#include <string>
#include <thread>
#include <chrono>
#include <iomanip>
#include <functional>
#include <sstream>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <iostream>
#include <vector>
#include <memory>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <unordered_map>

#include "core/Mesh.hpp"
#include "core/Shader.hpp"
#include "core/FirstPersonCamera.hpp"
#include "core/Frustum.hpp"
#include "core/FPSCounter.hpp"
#include "core/ResourceManager.hpp"
#include "core/physics/PhysicsWorld.hpp"
#include "objects/Player.hpp"
#include "objects/GameObject.hpp"
#include "objects/Plane.hpp"
#include "objects/Cube.hpp"
#include "core/TextRenderer.hpp"
#include "core/Version.hpp"
#include "core/AABBHelpers.hpp"
#include "objects/ObjectFactory.hpp"
#include "core/SpriteRenderer.hpp"
#include "core/LevelManager.hpp"

// ------------------------------------------------------------------
// Global pointers for console command access
// ------------------------------------------------------------------
Player* g_player = nullptr;
PhysicsWorld* g_physicsWorld = nullptr;
FirstPersonCamera* g_camera = nullptr;
bool g_debugMode = false;
LevelManager& g_levelManager = LevelManager::getInstance();
// ------------------------------------------------------------------
// Console state
// ------------------------------------------------------------------
bool consoleOpen = false;
std::string consoleInput;
std::vector<std::string> consoleHistory;
size_t historyIndex = 0;

// ------------------------------------------------------------------
// Window and input globals
// ------------------------------------------------------------------
const unsigned int SCR_WIDTH = 1920;
const unsigned int SCR_HEIGHT = 1080;
bool keys[1024] = {false};
bool firstMouse = true;
float lastX = SCR_WIDTH / 2.0f, lastY = SCR_HEIGHT / 2.0f;

// ------------------------------------------------------------------
// Forward declarations
// ------------------------------------------------------------------
void executeCommand(const std::string& cmd);
void character_callback(GLFWwindow* window, unsigned int codepoint);

// ------------------------------------------------------------------
// Execute console commands
// ------------------------------------------------------------------
void executeCommand(const std::string& cmd) {
    std::istringstream iss(cmd);
    std::string token;
    iss >> token;

    if (token == "dm") {
        g_debugMode = !g_debugMode;
        std::cout << "Debug mode " << (g_debugMode ? "ON" : "OFF") << std::endl;
    } else if (token == "d" && g_player) {
        int amount = 10;
        iss >> amount;
        g_player->takeDamage(amount);
        std::cout << "Player took " << amount << " damage. Health: " << g_player->getHealth() << std::endl;
    } else if (token == "h" && g_player) {
        int amount = 100;
        iss >> amount;
        g_player->heal(amount);
        std::cout << "Player healed " << amount << ". Health: " << g_player->getHealth() << std::endl;
    }
    // --- Level Commands ---
    else if (token == "loadlevel") {
        std::string levelName;
        iss >> levelName;
        if (!levelName.empty() && g_player) {
            g_levelManager.loadLevel(levelName);
            g_player->getRigidBody()->position = g_levelManager.getRespawnPosition();
            std::cout << "Loaded level: " << levelName << std::endl;
        }
    } else if (token == "levels") {
        g_levelManager.listLevels();
    } else if (token == "checkpoints") {
        g_levelManager.listCheckpoints();
    } else if (token == "setcp") {
        std::string cpName;
        iss >> cpName;
        if (!cpName.empty()) {
            g_levelManager.unlockCheckpoint(cpName);
        }
    } else if (token == "respawn") {
        if (g_player) g_levelManager.respawn(*g_player);
    }
    else {
        std::cout << "Unknown command: " << token << std::endl;
    }
}

// ------------------------------------------------------------------
// GLFW Callbacks
// ------------------------------------------------------------------
void character_callback(GLFWwindow* window, unsigned int codepoint) {
    if (!consoleOpen) return;
    if (codepoint >= 32 && codepoint <= 126) {
        consoleInput += static_cast<char>(codepoint);
    }
}

void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods) {
    if (action == GLFW_PRESS) {
        // Toggle console with P
        if (key == GLFW_KEY_0) {
            consoleOpen = !consoleOpen;
            consoleInput.clear();
        }

        if (consoleOpen) {
            // Console key handling
            if (key == GLFW_KEY_ENTER) {
                if (!consoleInput.empty()) {
                    consoleHistory.push_back(consoleInput);
                    historyIndex = consoleHistory.size();
                    executeCommand(consoleInput);
                    consoleInput.clear();
                }
            }
            else if (key == GLFW_KEY_BACKSPACE) {
                if (!consoleInput.empty()) consoleInput.pop_back();
            }
            else if (key == GLFW_KEY_UP) {
                if (historyIndex > 0) {
                    historyIndex--;
                    consoleInput = consoleHistory[historyIndex];
                }
            }
            else if (key == GLFW_KEY_DOWN) {
                if (historyIndex < consoleHistory.size()) {
                    historyIndex++;
                    if (historyIndex < consoleHistory.size())
                        consoleInput = consoleHistory[historyIndex];
                    else
                        consoleInput.clear();
                }
            }
            else if (key == GLFW_KEY_ESCAPE) {
                consoleOpen = false;
            }
            // Do not process game keys while console is open
            return;
        }
    }

    // Normal game input (only when console is closed)
    if (!consoleOpen) {
        if (key >= 0 && key < 1024) {
            if (action == GLFW_PRESS) keys[key] = true;
            else if (action == GLFW_RELEASE) keys[key] = false;
        }
    }
}

void mouse_callback(GLFWwindow* window, double xpos, double ypos) {
    if (firstMouse) {
        lastX = xpos;
        lastY = ypos;
        firstMouse = false;
    }
    float xoffset = xpos - lastX;
    float yoffset = lastY - ypos;
    lastX = xpos;
    lastY = ypos;
    FirstPersonCamera* cam = static_cast<FirstPersonCamera*>(glfwGetWindowUserPointer(window));
    if (cam) cam->processMouseMovement(xoffset, yoffset);
}




// ------------------------------------------------------------------
// Main
// ------------------------------------------------------------------
int main() {
    // GLFW / OpenGL init
    glfwInit();
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);

    GLFWwindow* window = glfwCreateWindow(SCR_WIDTH, SCR_HEIGHT, "OpenWorld", nullptr, nullptr);

    // Center the window on the screen
    GLFWmonitor* monitor = glfwGetPrimaryMonitor();
    const GLFWvidmode* mode = glfwGetVideoMode(monitor);
    if (mode) {
        int windowX = (mode->width - SCR_WIDTH) / 2;
        int windowY = (mode->height - SCR_HEIGHT) / 2;
        glfwSetWindowPos(window, windowX, windowY);
    }

    glfwMakeContextCurrent(window);
    glfwSetKeyCallback(window, key_callback);
    glfwSetCharCallback(window, character_callback);
    glfwSetCursorPosCallback(window, mouse_callback);
    glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_DISABLED);
    glfwSwapInterval(1);

    if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)) {
        std::cerr << "Failed to initialize GLAD" << std::endl;
        return -1;
    }
    SpriteRenderer::init();
    TextRenderer::init();
    LevelManager& g_levelManager = LevelManager::getInstance();

    Shader outlineShader("assets/shaders/outline/outline.vert",
                         "assets/shaders/outline/outline.frag",
                         "assets/shaders/outline/outline.geom");
    Shader shader("assets/shaders/basic.vert", "assets/shaders/basic.frag");

    std::cout << "GPU: " << glGetString(GL_RENDERER) << std::endl;
    std::cout << "OpenWorld " << RELEASE_STAGE << " v" << PROJECT_VERSION << std::endl;

    glEnable(GL_DEPTH_TEST);

    //Debugging
    //glDisable(GL_CULL_FACE);

    // Physics world
    PhysicsWorld physicsWorld;
    physicsWorld.setGravity(glm::vec3(0.0f, -8.0f, 0.0f));

    // Player
    Player player(glm::vec3(0.0f, 2.0f, 5.0f));
    physicsWorld.addRigidBody(player.getRigidBody());

    // Camera
    FirstPersonCamera camera(&player, glm::vec3(0.0f, 1.0f, 0.0f));
    glfwSetWindowUserPointer(window, &camera);

    // Set global pointers for console commands
    g_player = &player;
    g_physicsWorld = &physicsWorld;
    g_camera = &camera;

    // Ground plane
    Plane ground(100.0f, 100.0f);
    physicsWorld.addCollisionPlane(glm::vec3(0.0f, 1.0f, 0.0f), 0.0f);

    // All game objects
    std::vector<GameObject> objects;
    std::vector<std::pair<GameObject*, RigidBody*>> dynamicObjects;
    objects.reserve(1000);

    // ===== Level Setup =====
    Level tutorial;
    tutorial.name = "Tutorial";
    tutorial.initialSpawn = glm::vec3(0.0f, 2.0f, 5.0f);
    tutorial.checkpoints = {
        { glm::vec3(0.0f, 2.0f, 15.0f), "CP1" },
        { glm::vec3(20.0f, 2.0f, 30.0f), "CP2" },
        { glm::vec3(-20.0f, 5.0f, 50.0f), "CP3" }
    };
    //tutorial.onLoad = buildLevel1;  // optional – see note below

    g_levelManager.registerLevel(tutorial);
    g_levelManager.loadLevel("Tutorial");

    // Ensure player starts at level spawn (overwrites previous position)
    player.getRigidBody()->position = g_levelManager.getRespawnPosition();

    buildWorld(objects, physicsWorld, dynamicObjects, player);

    // FPS Counter and Frustum
    FPSCounter fpsCounter;
    Frustum frustum;

    // Main Loop
    float deltaTime = 0.0f;
    float lastFrame = 0.0f;
    while (!glfwWindowShouldClose(window)) {
        float currentFrame = glfwGetTime();
        deltaTime = currentFrame - lastFrame;
        lastFrame = currentFrame;

        glfwPollEvents();

        // Skip game input processing if console is open
        if (!consoleOpen) {
            // Input
            if (keys[GLFW_KEY_ESCAPE]) glfwSetWindowShouldClose(window, true);
            camera.processKeyboard(keys, deltaTime);

            if (keys[GLFW_KEY_R]) {
                g_levelManager.respawn(player);
            }

            // Door interaction (F key)
            if (keys[GLFW_KEY_F]) {
                glm::vec3 playerPos = player.getPosition();
                float interactRange = 20.0f;
                GameObject* closestDoor = nullptr;
                float closestDist = interactRange;
                for (auto& obj : objects) {
                    if (!obj.isAnimated) continue;
                    float dist = glm::distance(playerPos, obj.position);
                    if (dist < closestDist) {
                        closestDist = dist;
                        closestDoor = &obj;
                    }
                }
                if (closestDoor) {
                    closestDoor->isOpen = !closestDoor->isOpen;
                    AABB doorAABB;
                    doorAABB.min = closestDoor->position - closestDoor->halfExtents;
                    doorAABB.max = closestDoor->position + closestDoor->halfExtents;
                    if (closestDoor->isOpen) {
                        physicsWorld.removeStaticAABB(doorAABB);
                        closestDoor->hasCollision = false;
                    } else {
                        physicsWorld.addStaticAABB(doorAABB);
                        closestDoor->hasCollision = true;
                    }
                }
            }

            // Jump
            if (keys[GLFW_KEY_SPACE] && player.getRigidBody()->isGrounded) {
                player.getRigidBody()->velocity.y = 5.0f;
            }

            // Push / Pull (E key)
            if (keys[GLFW_KEY_E]) {
                glm::vec3 playerPos = player.getPosition();
                glm::vec3 forward = camera.getForward();
                float reach = 2.5f;
                AABB playerAABB;
                playerAABB.min = playerPos - glm::vec3(0.5f, 1.0f, 0.5f);
                playerAABB.max = playerPos + glm::vec3(0.5f, 1.0f, 0.5f);
                playerAABB.min += forward * reach * 0.5f;
                playerAABB.max += forward * reach * 0.5f;
                for (auto& [obj, rb] : dynamicObjects) {
                    AABB objAABB;
                    objAABB.min = obj->position - obj->halfExtents;
                    objAABB.max = obj->position + obj->halfExtents;
                    glm::vec3 correction;
                    if (AABBvsAABB(playerAABB, objAABB, correction)) {
                        float forceMagnitude = 500.0f * deltaTime;
                        glm::vec3 forceDir = (keys[GLFW_KEY_LEFT_SHIFT] || keys[GLFW_KEY_RIGHT_SHIFT])
                                                 ? glm::normalize(playerPos - obj->position)
                                                 : forward;
                        rb->applyForce(forceDir * forceMagnitude, deltaTime);
                        break;
                    }
                }
            }
        }

        // Physics step (always run, even when console open? You can choose)
        physicsWorld.step(deltaTime);

        // Update moving platforms
        for (auto& obj : objects) {
            if (!obj.isMoving) continue;
            glm::vec3 oldPos = obj.position;
            float totalDistance = glm::distance(obj.startPos, obj.endPos);
            if (totalDistance > 0.0f) {
                float deltaT = (obj.moveSpeed / totalDistance) * deltaTime;
                obj.moveT += deltaT * obj.moveDirection;
                if (obj.moveT >= 1.0f) { obj.moveT = 1.0f; obj.moveDirection = -1; }
                else if (obj.moveT <= 0.0f) { obj.moveT = 0.0f; obj.moveDirection = 1; }
            }
            glm::vec3 newPos = glm::mix(obj.startPos, obj.endPos, obj.moveT);
            glm::vec3 platformVelocity = (newPos - oldPos) / deltaTime;
            for (auto& [dynObj, rb] : dynamicObjects) {
                if (dynObj == &obj) { rb->position = newPos; rb->velocity = platformVelocity; break; }
            }
            obj.position = newPos;
        }

        // Carry objects on moving platforms
        static std::unordered_map<RigidBody*, GameObject*> bodyToPlatform;
        static std::unordered_map<RigidBody*, glm::vec3> relativeOffset;
        for (auto& obj : objects) {
            if (!obj.isMoving) continue;
            RigidBody* platformRB = nullptr;
            for (auto& [dynObj, rb] : dynamicObjects) if (dynObj == &obj) { platformRB = rb; break; }
            if (!platformRB) continue;
            AABB platformAABB;
            platformAABB.min = obj.position - obj.halfExtents;
            platformAABB.max = obj.position + obj.halfExtents;
            for (RigidBody* body : physicsWorld.getBodies()) {
                if (body == platformRB) continue;
                AABB bodyAABB;
                bodyAABB.min = body->position - body->halfExtents;
                bodyAABB.max = body->position + body->halfExtents;
                bool onTop = (bodyAABB.min.y >= platformAABB.max.y - 0.75f) &&
                             (bodyAABB.min.y <= platformAABB.max.y + 0.75f) &&
                             (bodyAABB.max.x > platformAABB.min.x && bodyAABB.min.x < platformAABB.max.x) &&
                             (bodyAABB.max.z > platformAABB.min.z && bodyAABB.min.z < platformAABB.max.z);
                bool isPlayer = (body == player.getRigidBody());
                if (onTop) {
                    if (bodyToPlatform[body] != &obj) {
                        bodyToPlatform[body] = &obj;
                        relativeOffset[body] = body->position - obj.position;
                    }
                    body->position.x = obj.position.x + relativeOffset[body].x;
                    body->position.z = obj.position.z + relativeOffset[body].z;
                    body->position.y = platformAABB.max.y + body->halfExtents.y;
                    if (isPlayer) {
                        glm::vec3 inputMove(0.0f);
                        glm::vec3 front = camera.getForward();
                        glm::vec3 right = glm::normalize(glm::cross(front, glm::vec3(0.0f,1.0f,0.0f)));
                        if (keys[GLFW_KEY_W]) inputMove += front;
                        if (keys[GLFW_KEY_S]) inputMove -= front;
                        if (keys[GLFW_KEY_A]) inputMove -= right;
                        if (keys[GLFW_KEY_D]) inputMove += right;
                        if (glm::length(inputMove) > 0.0f) {
                            inputMove = glm::normalize(inputMove);
                            float speed = (keys[GLFW_KEY_LEFT_SHIFT] || keys[GLFW_KEY_RIGHT_SHIFT]) ? 10.0f : 5.0f;
                            relativeOffset[body] += inputMove * speed * deltaTime;
                        }
                        body->velocity = platformRB->velocity;
                    } else {
                        body->velocity.x += platformRB->velocity.x;
                        body->velocity.z += platformRB->velocity.z;
                    }
                } else {
                    if (bodyToPlatform[body] == &obj) bodyToPlatform[body] = nullptr;
                }
            }
        }

        // Update visual positions
        for (auto& [obj, rb] : dynamicObjects) obj->position = rb->position;

        // Trigger detection
        AABB playerAABB;
        playerAABB.min = player.getPosition() - glm::vec3(0.5f, 1.0f, 0.5f);
        playerAABB.max = player.getPosition() + glm::vec3(0.5f, 1.0f, 0.5f);
        for (auto& obj : objects) {
            if (!obj.isTrigger) continue;
            AABB triggerAABB;
            triggerAABB.min = obj.position - obj.halfExtents;
            triggerAABB.max = obj.position + obj.halfExtents;
            if (checkAABBOverlap(playerAABB, triggerAABB)) {
                if (!obj.triggerFired && obj.onTriggerEnter) {
                    obj.triggerFired = true;
                    obj.onTriggerEnter(player);
                }
            } else {
                obj.triggerFired = false;
            }
        }

        // Animations (doors)
        for (auto& obj : objects) {
            if (!obj.isAnimated) continue;
            float targetRotation = obj.isOpen ? obj.openAngle : 0.0f;
            float diff = targetRotation - obj.currentRotation;
            obj.currentRotation += diff * obj.animationSpeed * deltaTime;
            if (fabs(diff) < 0.1f) obj.currentRotation = targetRotation;
        }

        if (player.getPosition().y < -10.0f) {
            g_levelManager.respawn(player);
            std::cout << "You fell off! Respawning..." << std::endl;
        }

        camera.update(deltaTime);

        // View / Projection
        glm::mat4 projection = glm::perspective(glm::radians(camera.getFOV()),
                                                (float)SCR_WIDTH / SCR_HEIGHT, 0.1f, 100.0f);
        glm::mat4 view = camera.getViewMatrix();
        frustum.extractPlanes(projection * view);

        // FPS & Window Title
        fpsCounter.update();
        char title[128];
        if (g_debugMode) {
            snprintf(title, sizeof(title), "OpenWorld %s v%s | FPS: %.1f | Pos: (%.1f, %.1f, %.1f) [DEBUG]",
                     RELEASE_STAGE, PROJECT_VERSION, fpsCounter.getCurrentFPS(),
                     player.getPosition().x, player.getPosition().y, player.getPosition().z);
        } else {
            snprintf(title, sizeof(title), "OpenWorld %s v%s | FPS: %.1f",
                     RELEASE_STAGE, PROJECT_VERSION, fpsCounter.getCurrentFPS());
        }
        glfwSetWindowTitle(window, title);

        // Render
        glClearColor(0.2f, 0.3f, 0.3f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

        // Ground plane
        shader.use();
        shader.setMat4("projection", projection);
        shader.setMat4("view", view);
        glm::mat4 model = glm::translate(glm::mat4(1.0f), glm::vec3(0.0f, 0.0f, 0.0f));
        shader.setMat4("model", model);
        shader.setVec3("objectColor", glm::vec3(0.0f, 1.0f, 1.0f));
        ground.draw();

        // All other objects with outline shader
        outlineShader.use();
        outlineShader.setMat4("projection", projection);
        outlineShader.setMat4("view", view);
        outlineShader.setVec3("edgeColor", glm::vec3(0.0f, 0.0f, 0.0f));
        outlineShader.setFloat("edgeWidth", 0.04f);

        glm::vec3 camPos = camera.getPosition();
        for (auto& obj : objects) {
            glm::vec3 min = obj.position - obj.halfExtents;
            glm::vec3 max = obj.position + obj.halfExtents;
            if (!frustum.isAABBVisible(min, max)) continue;

            float dist = glm::distance(camPos, obj.position);
            int lodLevel = 0;
            if (dist > 30.0f) lodLevel = 2;
            else if (dist > 15.0f) lodLevel = 1;

            glm::vec3 color;
            if (obj.isTrigger) color = glm::vec3(0.0f, 1.0f, 0.0f);
            else if (obj.isMoving) color = glm::vec3(1.0f, 1.0f, 0.0f);
            else if (obj.hasCollision) color = glm::vec3(1.0f, 0.0f, 0.0f);
            else color = glm::vec3(0.5f, 0.5f, 0.5f);

            glm::mat4 model = glm::mat4(1.0f);
            if (obj.isAnimated) {
                model = glm::translate(model, obj.position + obj.hingeOffset);
                model = glm::rotate(model, glm::radians(obj.currentRotation), obj.rotationAxis);
                model = glm::translate(model, -obj.hingeOffset);
                model = glm::scale(model, obj.halfExtents * 2.0f);
            } else {
                model = glm::translate(model, obj.position);
                if (obj.rotation != glm::vec3(0.0f)) {
                    model = glm::rotate(model, glm::radians(obj.rotation.x), glm::vec3(1.0f, 0.0f, 0.0f));
                    model = glm::rotate(model, glm::radians(obj.rotation.y), glm::vec3(0.0f, 1.0f, 0.0f));
                    model = glm::rotate(model, glm::radians(obj.rotation.z), glm::vec3(0.0f, 0.0f, 1.0f));
                }
                float angle = (obj.halfExtents == glm::vec3(0.0f)) ? currentFrame * 0.5f : 0.0f;
                model = glm::rotate(model, angle, glm::vec3(0.0f, 1.0f, 0.0f));
                if (obj.halfExtents != glm::vec3(0.5f))
                    model = glm::scale(model, obj.halfExtents * 2.0f);
            }
            outlineShader.setMat4("model", model);
            outlineShader.setVec3("objectColor", color);
            obj.draw(lodLevel);
        }



        // Console overlay
        if (consoleOpen) {
            std::string prompt = "> " + consoleInput + (fmod(glfwGetTime(), 1.0) > 0.5 ? "_" : " ");
            //The size may be to small
            TextRenderer::print(prompt, 10.0f, 50.0f, 1.0f, glm::vec3(1.0f, 1.0f, 1.0f));
            int linesToShow = 10;
            size_t start = (consoleHistory.size() > linesToShow) ? consoleHistory.size() - linesToShow : 0;
            for (size_t i = start; i < consoleHistory.size(); ++i) {
                float y = 80.0f + (i - start) * 20.0f;
                TextRenderer::print(consoleHistory[i], 10.0f, y, 1.0f, glm::vec3(0.8f));
            }
        }

        // --- UI Rendering ---
        float healthPercent = player.getHealth() / 100.0f;
        float barX = 50.0f;
        float barY = SCR_HEIGHT - 100.0f;
        float barWidth = 200.0f;
        float barHeight = 20.0f;

        // Background (dark grey)
        SpriteRenderer::drawRectangle(barX, barY, barWidth, barHeight, glm::vec3(0.2f));
        // Foreground (red health)
        SpriteRenderer::drawRectangle(barX, barY, barWidth * healthPercent, barHeight, glm::vec3(0.8f, 0.2f, 0.2f));

        // Draw crosshair (simple dot at screen center)
        float crossSize = 10.0f;
        SpriteRenderer::drawRectangle(SCR_WIDTH/2.0f - crossSize/2.0f, SCR_HEIGHT/2.0f - crossSize/2.0f,
                                      crossSize, crossSize, glm::vec3(1.0f));

        // Flush all sprites in one draw call
        SpriteRenderer::flush();

        // Keep TextRenderer for text (FPS, health text)
        char healthText[32];
        snprintf(healthText, sizeof(healthText), "Health: %d", player.getHealth());
        TextRenderer::print(healthText, barX, barY - 30.0f, 1.5f, glm::vec3(1.0f));

        TextRenderer::printFPS(fpsCounter.getCurrentFPS(), 50.0f, SCR_HEIGHT - 1050.0f, 2.0f);

        //Debug print
        //TextRenderer::print("TEST TEXT", 1700.0f, 100.0f, 2.0f, glm::vec3(1.0f, 0.0f, 0.0f));

        if (g_debugMode) {
            shader.use();
            shader.setMat4("projection", projection);
            shader.setMat4("view", view);

            // Static AABBs (green)
            for (const auto& aabb : physicsWorld.getStaticAABBs()) {
                glm::mat4 model = glm::translate(glm::mat4(1.0f), (aabb.min + aabb.max) * 0.5f);
                model = glm::scale(model, (aabb.max - aabb.min));
                shader.setMat4("model", model);
                shader.setVec3("objectColor", glm::vec3(0, 1, 0));
                glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
                Cube::generateHighPoly(0.5f).draw();
                glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
            }

            // Oriented colliders (blue)
            for (const auto& oc : physicsWorld.getOrientedColliders()) {
                glm::mat4 model = glm::translate(glm::mat4(1.0f), oc.position);
                model = model * glm::mat4(oc.rotation);
                model = glm::scale(model, oc.halfExtents * 2.0f);
                shader.setMat4("model", model);
                shader.setVec3("objectColor", glm::vec3(0, 0, 1));
                glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
                Cube::generateHighPoly(0.5f).draw();
                glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
            }

            // Dynamic bodies (yellow)
            for (const auto* body : physicsWorld.getBodies()) {
                glm::mat4 model = glm::translate(glm::mat4(1.0f), body->position);
                model = glm::scale(model, body->halfExtents * 2.0f);
                shader.setMat4("model", model);
                shader.setVec3("objectColor", glm::vec3(1, 1, 0));
                glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
                Cube::generateHighPoly(0.5f).draw();
                glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
            }
        }
        glfwPollEvents();
        glfwSwapBuffers(window);
    }

    TextRenderer::shutdown();
    SpriteRenderer::shutdown();
    glfwTerminate();
    return 0;
}