
//The file structure
//openworld_alpha/                      # orginal name
//├── CMakeLists.txt                    # Build configuration
//├── main.cpp                          # Program entry, window, main loop, orchestration
//│
//├── core/                             # Engine‑level reusable components
//│   ├── AABBHelpers.hpp               # Shared AABB overlap & correction functions
//│   ├── Mesh.hpp / Mesh.cpp           # VAO/VBO wrapper, draw calls, move semantics
//│   ├── Shader.hpp / Shader.cpp       # Shader loading, compiling, uniform setting
//│   ├── FirstPersonCamera.hpp / .cpp  # Player camera, movement, sprint, FOV
//│   ├── Frustum.hpp / Frustum.cpp     # Frustum culling for rendering optimisation
//│   ├── FPSCounter.hpp / FPSCounter.cpp # FPS measurement (used in window title)
//│   ├── ResourceManager.hpp / .cpp    # Placeholder for future asset management
//│   ├── TextRenderer.hpp / TextRenderer.cpp # On‑screen text (currently non‑functional)
//│   ├── Version.hpp                   # Version and release stage macros
//│   │
//│   ├── physics/                      # Physics subsystem
//│   │   ├── RigidBody.hpp / .cpp      # Position, velocity, mass, halfExtents, forces
//│   │   ├── Collider.hpp / .cpp       # AABB and Sphere colliders (AABB used everywhere)
//│   │   └── PhysicsWorld.hpp / .cpp   # Gravity, collision resolution, kinematic support
//│   │
//│   └── core/                         # Third‑party single‑header libs
//│       └── stb_easy_font.h           # Bitmap font rendering (used by TextRenderer)
//│
//├── objects/                          # Game‑specific object logic
//│   ├── GameObject.hpp / .cpp         # Base class for all interactive objects
//│   ├── Player.hpp / .cpp             # Player specific (RigidBody + height)
//│   ├── Cube.hpp / .cpp               # Cube mesh generator (LOD variants)
//│   ├── Plane.hpp / .cpp              # Ground plane mesh
//│   ├── wall.hpp / wall.cpp           # Wall mesh (box with custom dimensions)
//│   └── ObjectFactory.hpp / .cpp      # World building: creates all objects (cubes, walls, triggers, etc.)
//│
//├── assets/                           # Raw data files (copied to build dir)
//│   ├── models/                       # (empty – reserved for .obj/.gltf files)
//│   ├── textures/                     # (empty – reserved for images)
//│   └── shaders/
//│       ├── basic.vert                # Simple vertex shader (uses objectColor uniform)
//│       ├── basic.frag                # Simple fragment shader
//│       ├── outline/                  # Outline effect shaders (barycentric edge detection)
//│       │   ├── outline.vert
//│       │   ├── outline.geom
//│       │   └── outline.frag
//│       └── text/                     # 2D text shaders (for TextRenderer)
//│           ├── text.vert
//│           └── text.frag
//│
//├── glad/                             # OpenGL loader (generated by GLAD)
//│   ├── include/
//│   │   ├── KHR/
//│   │   └── glad/
//│   └── src/
//│       └── glad.c
//│
//└── build/                            # CMake output (not shown in source control)
// main.cpp

// 1 unit = 1 meter

// For GLFW Keys: https://github.com/glfw/glfw/blob/master/include/GLFW/glfw3.h

// main.cpp
// Complete rewrite with Menu / Loading / Game states

#include <cstring>
#include <string>
#include <thread>
#include <chrono>
#include <iomanip>
#include <functional>
#include <sstream>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <iostream>
#include <vector>
#include <memory>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <unordered_map>
#include <cmath>

#include "core/Mesh.hpp"
#include "core/Shader.hpp"
#include "core/FirstPersonCamera.hpp"
#include "core/Frustum.hpp"
#include "core/FPSCounter.hpp"
#include "core/ResourceManager.hpp"
#include "core/physics/PhysicsWorld.hpp"
#include "objects/Player.hpp"
#include "objects/GameObject.hpp"
#include "objects/Plane.hpp"
#include "objects/Cube.hpp"
#include "core/TextRenderer.hpp"
#include "core/Version.hpp"
#include "core/AABBHelpers.hpp"
#include "objects/ObjectFactory.hpp"
#include "core/SpriteRenderer.hpp"
#include "core/LevelManager.hpp"

// ------------------------------------------------------------------
// App state
// ------------------------------------------------------------------
enum class AppState {
    MENU,
    LOADING,
    GAME
};
AppState appState = AppState::MENU;

// ------------------------------------------------------------------
// Global pointers (only valid when in GAME state)
// ------------------------------------------------------------------
Player*                 g_player            = nullptr;
PhysicsWorld*           g_physicsWorld      = nullptr;
FirstPersonCamera*      g_camera            = nullptr;
bool                    g_debugMode         = false;
LevelManager&           g_levelManager      = LevelManager::getInstance();

// ------------------------------------------------------------------
// 3D world ownership (destroyed when leaving game)
// ------------------------------------------------------------------
std::unique_ptr<Player>                     g_playerPtr;
std::vector<GameObject>                     g_worldObjects;
std::vector<std::pair<GameObject*, RigidBody*>> g_dynamicObjects;
PhysicsWorld                                g_physics;          // the actual physics world
std::unique_ptr<FirstPersonCamera>          g_cameraPtr;
std::unique_ptr<Plane>                      g_groundPlane;

// ------------------------------------------------------------------
// Console state
// ------------------------------------------------------------------
bool consoleOpen = false;
std::string consoleInput;
std::vector<std::string> consoleHistory;
size_t historyIndex = 0;

// ------------------------------------------------------------------
// Window and input globals
// ------------------------------------------------------------------
const unsigned int SCR_WIDTH  = 1920;
const unsigned int SCR_HEIGHT = 1080;
bool keys[1024] = {false};
bool firstMouse = true;
float lastX = SCR_WIDTH / 2.0f, lastY = SCR_HEIGHT / 2.0f;

// Mouse for menu interaction
double mouseX = SCR_WIDTH / 2.0;
double mouseY = SCR_HEIGHT / 2.0;
bool mouseButtons[8] = {false};
bool mouseJustPressed[8] = {false};

glm::mat4 g_viewMatrix(1.0f);
glm::mat4 g_projectionMatrix(1.0f);
extern Shader* shader3D;
// ------------------------------------------------------------------
// Forward declarations
// ------------------------------------------------------------------
void executeCommand(const std::string& cmd);
void character_callback(GLFWwindow* window, unsigned int codepoint);
void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods);
void mouse_button_callback(GLFWwindow* window, int button, int action, int mods);
void cursor_pos_callback(GLFWwindow* window, double xpos, double ypos);

bool startGame(GLFWwindow* window);
void cleanupGame(GLFWwindow* window);

// ------------------------------------------------------------------
// Console command execution
// ------------------------------------------------------------------
void executeCommand(const std::string& cmd) {
    std::istringstream iss(cmd);
    std::string token;
    iss >> token;

    if (token == "dm") {
        g_debugMode = !g_debugMode;
        std::cout << "Debug mode " << (g_debugMode ? "ON" : "OFF") << std::endl;
    } else if (token == "d" && g_player) {
        int amount = 10;
        iss >> amount;
        g_player->takeDamage(amount);
        std::cout << "Player took " << amount << " damage. Health: " << g_player->getHealth() << std::endl;
    } else if (token == "h" && g_player) {
        int amount = 100;
        iss >> amount;
        g_player->heal(amount);
        std::cout << "Player healed " << amount << ". Health: " << g_player->getHealth() << std::endl;
    } else if (token == "ll") {
        std::string levelName;
        iss >> levelName;
        if (!levelName.empty() && g_player) {
            g_levelManager.loadLevel(levelName);
            g_player->getRigidBody()->position = g_levelManager.getRespawnPosition();
            std::cout << "Loaded level: " << levelName << std::endl;
        }
    } else if (token == "levels") {
        g_levelManager.listLevels();
    } else if (token == "checkpoints") {
        g_levelManager.listCheckpoints();
    } else if (token == "setcp") {
        std::string cpName;
        iss >> cpName;
        if (!cpName.empty()) {
            g_levelManager.unlockCheckpoint(cpName);
        }
    } else if (token == "respawn") {
        if (g_player) g_levelManager.respawn(*g_player);
    } else {
        std::cout << "Unknown command: " << token << std::endl;
    }
}

// ------------------------------------------------------------------
// GLFW Callbacks
// ------------------------------------------------------------------
void character_callback(GLFWwindow* window, unsigned int codepoint) {
    if (!consoleOpen) return;
    if (codepoint >= 32 && codepoint <= 126) {
        consoleInput += static_cast<char>(codepoint);
    }
}

void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods) {
    // Console toggle (works in all states)
    if (key == GLFW_KEY_0 && action == GLFW_PRESS) {
        consoleOpen = !consoleOpen;
        consoleInput.clear();
        return;
    }

    if (consoleOpen) {
        if (action == GLFW_PRESS) {
            if (key == GLFW_KEY_ENTER) {
                if (!consoleInput.empty()) {
                    consoleHistory.push_back(consoleInput);
                    historyIndex = consoleHistory.size();
                    executeCommand(consoleInput);
                    consoleInput.clear();
                }
            } else if (key == GLFW_KEY_BACKSPACE) {
                if (!consoleInput.empty()) consoleInput.pop_back();
            } else if (key == GLFW_KEY_UP) {
                if (historyIndex > 0) {
                    historyIndex--;
                    consoleInput = consoleHistory[historyIndex];
                }
            } else if (key == GLFW_KEY_DOWN) {
                if (historyIndex < consoleHistory.size()) {
                    historyIndex++;
                    if (historyIndex < consoleHistory.size())
                        consoleInput = consoleHistory[historyIndex];
                    else
                        consoleInput.clear();
                }
            } else if (key == GLFW_KEY_ESCAPE) {
                consoleOpen = false;
            }
        }
        return;
    }

    // Normal game / menu input (console closed)
    if (action == GLFW_PRESS) {
        if (key >= 0 && key < 1024) keys[key] = true;
        if (key == GLFW_KEY_ESCAPE && appState == AppState::GAME) {
            cleanupGame(window);
            appState = AppState::MENU;
            keys[key] = false; // prevent immediate re‑trigger
        }
    } else if (action == GLFW_RELEASE) {
        if (key >= 0 && key < 1024) keys[key] = false;
    }
}

void mouse_button_callback(GLFWwindow* window, int button, int action, int mods) {
    //std::cout << "Mouse button " << button << " action " << action << std::endl;
    if (button >= 0 && button < 8) {
        if (action == GLFW_PRESS) {
            mouseButtons[button] = true;
            mouseJustPressed[button] = true;
        } else if (action == GLFW_RELEASE) {
            mouseButtons[button] = false;
        }
    }
}

void cursor_pos_callback(GLFWwindow* window, double xpos, double ypos) {
    mouseX = xpos;
    mouseY = ypos;

    // Only update camera in game state (console closed)
    if (appState == AppState::GAME && !consoleOpen && g_camera) {
        if (firstMouse) {
            lastX = xpos;
            lastY = ypos;
            firstMouse = false;
        }
        float xoffset = xpos - lastX;
        float yoffset = lastY - ypos;
        lastX = xpos;
        lastY = ypos;
        g_camera->processMouseMovement(xoffset, yoffset);
    }
}

// ------------------------------------------------------------------
// Game lifecycle
// ------------------------------------------------------------------
bool startGame(GLFWwindow* window) {
    //std::cout << "startGame called" << std::endl;
    // 1. Create player (owned by g_playerPtr)
    g_playerPtr = std::make_unique<Player>(glm::vec3(0.0f, 2.0f, 5.0f));
    g_player = g_playerPtr.get();

    // 2. Physics world (global object, reset first)
    g_physics = PhysicsWorld();
    g_physics.setGravity(glm::vec3(0.0f, -8.0f, 0.0f));
    g_physics.addRigidBody(g_player->getRigidBody());
    g_physicsWorld = &g_physics;

    // 3. Camera (owned by g_cameraPtr)
    g_cameraPtr = std::make_unique<FirstPersonCamera>(g_player, glm::vec3(0.0f, 1.0f, 0.0f));
    g_camera = g_cameraPtr.get();
    glfwSetWindowUserPointer(window, g_camera);

    // 4. Ground plane
    g_groundPlane = std::make_unique<Plane>(100.0f, 100.0f);
    g_physics.addCollisionPlane(glm::vec3(0.0f, 1.0f, 0.0f), 0.0f);

    // 5. Level definition
    // Tutorial
    Level tutorial;
    tutorial.name = "Tutorial";
    tutorial.initialSpawn = glm::vec3(0.0f, 2.0f, 5.0f);
    tutorial.checkpoints = {
        { glm::vec3(50.0f, 2.0f, 50.0f), "CP1" },
        { glm::vec3(-50.0f, 2.0f, -50.0f), "CP2" },
        { glm::vec3(-50.0f, 2.0f, 50.0f), "CP3" },
        { glm::vec3(50.0f, 2.0f, -50.0f), "CP4" }
    };
    g_levelManager.registerLevel(tutorial);
    g_levelManager.loadLevel("Tutorial");
    g_player->getRigidBody()->position = g_levelManager.getRespawnPosition();

    // Level 1
    Level level1;
    level1.name = "Level1";
    level1.initialSpawn = glm::vec3(100.0f, 2.0f, 100.0f);
    level1.checkpoints = {
        { glm::vec3(50.0f, 2.0f, 70.0f), "L1_CP1" },
        { glm::vec3(80.0f, 2.0f, 80.0f), "L1_CP2" },
        { glm::vec3(100.0f, 5.0f, 100.0f), "L1_CP3" },
        { glm::vec3(120.0f, 2.0f, 120.0f), "L1_CP4" }
    };
    g_levelManager.registerLevel(level1);

    // 6. Objects
    g_worldObjects.clear();
    g_dynamicObjects.clear();
    g_worldObjects.reserve(1000);
    buildWorld(g_worldObjects, g_physics, g_dynamicObjects, *g_player);

    // 7. Hide mouse cursor, reset first-mouse
    glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_DISABLED);
    firstMouse = true;
    //std::cout << "startGame called" << std::endl;
    return true;
}

void cleanupGame(GLFWwindow* window) {
    // 1. Free dynamic RigidBodies (we own them via new in ObjectFactory)
    for (auto& pair : g_dynamicObjects) {
        delete pair.second;
    }
    g_dynamicObjects.clear();

    // 2. Clear objects (meshes freed automatically)
    g_worldObjects.clear();

    // 3. Reset unique_ptrs (destroys Player, Camera, Ground)
    g_playerPtr.reset();
    g_cameraPtr.reset();
    g_groundPlane.reset();

    // 4. Reset globals
    g_player = nullptr;
    g_physicsWorld = nullptr;
    g_camera = nullptr;

    // 5. Show cursor again
    glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_NORMAL);
}

// ------------------------------------------------------------------
// Main
// ------------------------------------------------------------------
int main() {
    // GLFW / OpenGL init
    glfwInit();
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);

    GLFWwindow* window = glfwCreateWindow(SCR_WIDTH, SCR_HEIGHT, "OpenWorld Engine", nullptr, nullptr);
    if (!window) {
        glfwTerminate();
        return -1;
    }

    // Center the window
    GLFWmonitor* monitor = glfwGetPrimaryMonitor();
    const GLFWvidmode* mode = glfwGetVideoMode(monitor);
    if (mode) {
        glfwSetWindowPos(window, (mode->width - SCR_WIDTH) / 2, (mode->height - SCR_HEIGHT) / 2);
    }

    glfwMakeContextCurrent(window);
    glfwSetKeyCallback(window, key_callback);
    glfwSetCharCallback(window, character_callback);
    glfwSetMouseButtonCallback(window, mouse_button_callback);
    glfwSetCursorPosCallback(window, cursor_pos_callback);
    glfwSwapInterval(1);

    if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)) {
        std::cerr << "Failed to initialize GLAD" << std::endl;
        return -1;
    }

    SpriteRenderer::init();
    TextRenderer::init();

    // Shaders for 3D (created once, reused across sessions)
    Shader outlineShader("assets/shaders/outline/outline.vert",
                         "assets/shaders/outline/outline.frag",
                         "assets/shaders/outline/outline.geom");
    Shader basicShader("assets/shaders/basic.vert", "assets/shaders/basic.frag");

    std::cout << "GPU: " << glGetString(GL_RENDERER) << std::endl;
    std::cout << "OpenWorld Engine" << RELEASE_STAGE << " v" << PROJECT_VERSION << std::endl;

    glEnable(GL_DEPTH_TEST);
    glfwSetMouseButtonCallback(window, mouse_button_callback);
    std::cout << "Mouse button callback set." << std::endl;
    // Main loop
    float deltaTime = 0.0f;
    float lastFrame = 0.0f;
    while (!glfwWindowShouldClose(window)) {
        float currentFrame = glfwGetTime();
        deltaTime = currentFrame - lastFrame;
        lastFrame = currentFrame;

        glfwPollEvents();
        //std::cout << "TextRenderer init done. Testing print..." << std::endl;
        //TextRenderer::print("A", 100, 200, 2.0f, glm::vec3(1,1,1));
        //std::cout << "ENTER=" << keys[GLFW_KEY_ENTER]
                  //<< " SPACE=" << keys[GLFW_KEY_SPACE] << std::endl;

        // Reset mouse just‑pressed flags each frame
        for (int i = 0; i < 8; ++i) mouseJustPressed[i] = false;

        // Clear screen
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

        if (appState == AppState::MENU) {
            // ── MENU ──────────────────────────────────────────
            glClearColor(0.1f, 0.1f, 0.15f, 1.0f);
            glClear(GL_COLOR_BUFFER_BIT);

            // Titles
            TextRenderer::print("OpenWorld Engine ", SCR_WIDTH/2.0f - 900.0f, 10.0f, 5.0f, glm::vec3(0.9f, 0.9f, 1.0f));
            TextRenderer::print("v1.0.00", SCR_WIDTH/2.0f - 500.0f, 50.0f, 2.0f, glm::vec3(0.9f, 0.9f, 1.0f));

            TextRenderer::print("[Game Title]", 100, 200, 5.0f, glm::vec3(1,1,1));
            TextRenderer::print("v0.0.00", 400, 250, 2.0f, glm::vec3(1,1,1));

                // Draw a white rectangle at the same spot using TextRenderer's shader
            //GLint vp[4];
            //glGetIntegerv(GL_VIEWPORT, vp);
            //glm::mat4 ortho = glm::ortho(0.0f, (float)vp[2], (float)vp[3], 0.0f);

            // Button layout
            float baseX = SCR_WIDTH/2.0f - 150.0f;   // original center (810)
            float shift = -750.0f;                   // how far you moved them left
            float btnLeft = baseX + shift;           // actual left edge = 60
            float btnW = 300.0f, btnH = 50.0f;
            float btnYplay = SCR_HEIGHT/2.0f;        // unchanged
            float btnYquit = btnYplay + 80.0f;

            // Draw buttons at the new position
            SpriteRenderer::drawRectangle(btnLeft, btnYplay, btnW, btnH, glm::vec3(0.2f, 0.6f, 0.2f));
            SpriteRenderer::drawRectangle(btnLeft, btnYquit, btnW, btnH, glm::vec3(0.6f, 0.2f, 0.2f));
            SpriteRenderer::flush();

            // Draw text labels
            TextRenderer::print("Play", btnLeft + 100.0f, btnYplay + 10.0f, 5.0f, glm::vec3(1.0f));
            TextRenderer::print("Quit", btnLeft + 100.0f, btnYquit + 10.0f, 5.0f, glm::vec3(1.0f));

            // Hover highlight (using the same btnLeft)
            if (mouseX >= btnLeft && mouseX <= btnLeft + btnW) {
                if (mouseY >= btnYplay && mouseY <= btnYplay + btnH) {
                    SpriteRenderer::drawRectangle(btnLeft-2, btnYplay-2, btnW+4, btnH+4, glm::vec3(1,1,1));
                } else if (mouseY >= btnYquit && mouseY <= btnYquit + btnH) {
                    SpriteRenderer::drawRectangle(btnLeft-2, btnYquit-2, btnW+4, btnH+4, glm::vec3(1,1,1));
                }
            }

            //SpriteRenderer::flush();   // draw the highlights now

            // Keyboard fallback
            static bool enterWasDown = false;
            bool enterNow = keys[GLFW_KEY_ENTER];
            if (enterNow && !enterWasDown) {
                //std::cout << "ENTER pressed – starting game" << std::endl;
                appState = AppState::LOADING;
            }
            enterWasDown = enterNow;
            // Keyboard action – use SPACE since it's proven to work
            if (keys[GLFW_KEY_SPACE]) {
                //std::cout << "SPACE pressed – entering LOADING" << std::endl;
                appState = AppState::LOADING;
            }
            if (mouseJustPressed[GLFW_MOUSE_BUTTON_LEFT]) {
                std::cout << "Click at (" << mouseX << "," << mouseY << ")" << std::endl;
                if (mouseX >= btnLeft && mouseX <= btnLeft + btnW) {
                    if (mouseY >= btnYplay && mouseY <= btnYplay + btnH) {
                        std::cout << ">>> PLAY clicked <<<" << std::endl;
                        appState = AppState::LOADING;
                    } else if (mouseY >= btnYquit && mouseY <= btnYquit + btnH) {
                        std::cout << ">>> QUIT clicked <<<" << std::endl;
                        glfwSetWindowShouldClose(window, GLFW_TRUE);
                    }
                }
            }

            glfwSwapBuffers(window);

        } else if (appState == AppState::LOADING) {
            // ── LOADING (with minimum delay) ─────────────────────
            static int loadingFrames = 0;
            const int requiredFrames = 60;

            // Draw a black frame (and a simple "Loading..." text for feedback)
            SpriteRenderer::drawRectangle(0, 0, SCR_WIDTH, SCR_HEIGHT, glm::vec3(0.0f));
            SpriteRenderer::flush();
            TextRenderer::print("Loading...", 0, 0, 10.0f, glm::vec3(1,1,1));

            if (loadingFrames == 0) {
                // First time in this state – build the 3D world
                if (!startGame(window)) {
                    std::cerr << "Failed to start game!" << std::endl;
                    appState = AppState::MENU;
                    loadingFrames = 0;
                }
            }

            loadingFrames++;

            if (loadingFrames >= requiredFrames) {
                // Delay finished – enter game
                loadingFrames = 0;
                appState = AppState::GAME;
                deltaTime = 0.0f;
                lastFrame = glfwGetTime();
            }

            glfwSwapBuffers(window);
        }
        else if (appState == AppState::GAME && g_player) {
            // ── GAME ──────────────────────────────────────────
            // Existing gameplay code, but using g_* globals



            glClearColor(0.2f, 0.3f, 0.3f, 1.0f);
            glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

            // Input (skip if console open)
            if (!consoleOpen) {
                if (keys[GLFW_KEY_R]) {
                    g_levelManager.respawn(*g_player);
                }

                // Door interaction
                if (keys[GLFW_KEY_F]) {
                    glm::vec3 playerPos = g_player->getPosition();
                    float interactRange = 20.0f;
                    GameObject* closestDoor = nullptr;
                    float closestDist = interactRange;
                    for (auto& obj : g_worldObjects) {
                        if (!obj.isAnimated) continue;
                        float dist = glm::distance(playerPos, obj.position);
                        if (dist < closestDist) {
                            closestDist = dist;
                            closestDoor = &obj;
                        }
                    }
                    if (closestDoor) {
                        closestDoor->isOpen = !closestDoor->isOpen;
                        AABB doorAABB;
                        doorAABB.min = closestDoor->position - closestDoor->halfExtents;
                        doorAABB.max = closestDoor->position + closestDoor->halfExtents;
                        if (closestDoor->isOpen) {
                            g_physics.removeStaticAABB(doorAABB);
                            closestDoor->hasCollision = false;
                        } else {
                            g_physics.addStaticAABB(doorAABB);
                            closestDoor->hasCollision = true;
                        }
                    }
                }

                // Jump
                if (keys[GLFW_KEY_SPACE] && g_player->getRigidBody()->isGrounded) {
                    g_player->getRigidBody()->velocity.y = 5.0f;
                }

                // Push / Pull
                if (keys[GLFW_KEY_E]) {
                    glm::vec3 playerPos = g_player->getPosition();
                    glm::vec3 forward = g_camera->getForward();
                    float reach = 2.5f;
                    AABB playerAABB;
                    playerAABB.min = playerPos - glm::vec3(0.5f, 1.0f, 0.5f);
                    playerAABB.max = playerPos + glm::vec3(0.5f, 1.0f, 0.5f);
                    playerAABB.min += forward * reach * 0.5f;
                    playerAABB.max += forward * reach * 0.5f;
                    for (auto& [obj, rb] : g_dynamicObjects) {
                        AABB objAABB;
                        objAABB.min = obj->position - obj->halfExtents;
                        objAABB.max = obj->position + obj->halfExtents;
                        glm::vec3 correction;
                        if (AABBvsAABB(playerAABB, objAABB, correction)) {
                            float forceMagnitude = 500.0f * deltaTime;
                            glm::vec3 forceDir = (keys[GLFW_KEY_LEFT_SHIFT] || keys[GLFW_KEY_RIGHT_SHIFT])
                                                     ? glm::normalize(playerPos - obj->position)
                                                     : forward;
                            rb->applyForce(forceDir * forceMagnitude, deltaTime);
                            break;
                        }
                    }
                }
            }

            // Player movement (WASD, sprint)
            g_camera->processKeyboard(keys, deltaTime);

            // Physics step
            g_physics.step(deltaTime);

            // Moving platforms
            for (auto& obj : g_worldObjects) {
                if (!obj.isMoving) continue;
                glm::vec3 oldPos = obj.position;
                float totalDistance = glm::distance(obj.startPos, obj.endPos);
                if (totalDistance > 0.0f) {
                    float deltaT = (obj.moveSpeed / totalDistance) * deltaTime;
                    obj.moveT += deltaT * obj.moveDirection;
                    if (obj.moveT >= 1.0f) { obj.moveT = 1.0f; obj.moveDirection = -1; }
                    else if (obj.moveT <= 0.0f) { obj.moveT = 0.0f; obj.moveDirection = 1; }
                }
                glm::vec3 newPos = glm::mix(obj.startPos, obj.endPos, obj.moveT);
                glm::vec3 platformVelocity = (newPos - oldPos) / deltaTime;
                for (auto& [dynObj, rb] : g_dynamicObjects) {
                    if (dynObj == &obj) { rb->position = newPos; rb->velocity = platformVelocity; break; }
                }
                obj.position = newPos;
            }

            // Carry objects on moving platforms
            static std::unordered_map<RigidBody*, GameObject*> bodyToPlatform;
            static std::unordered_map<RigidBody*, glm::vec3> relativeOffset;
            for (auto& obj : g_worldObjects) {
                if (!obj.isMoving) continue;
                RigidBody* platformRB = nullptr;
                for (auto& [dynObj, rb] : g_dynamicObjects) if (dynObj == &obj) { platformRB = rb; break; }
                if (!platformRB) continue;
                AABB platformAABB;
                platformAABB.min = obj.position - obj.halfExtents;
                platformAABB.max = obj.position + obj.halfExtents;
                for (RigidBody* body : g_physics.getBodies()) {
                    if (body == platformRB) continue;
                    AABB bodyAABB;
                    bodyAABB.min = body->position - body->halfExtents;
                    bodyAABB.max = body->position + body->halfExtents;
                    bool onTop = (bodyAABB.min.y >= platformAABB.max.y - 0.75f) &&
                                 (bodyAABB.min.y <= platformAABB.max.y + 0.75f) &&
                                 (bodyAABB.max.x > platformAABB.min.x && bodyAABB.min.x < platformAABB.max.x) &&
                                 (bodyAABB.max.z > platformAABB.min.z && bodyAABB.min.z < platformAABB.max.z);
                    bool isPlayer = (body == g_player->getRigidBody());
                    if (onTop) {
                        if (bodyToPlatform[body] != &obj) {
                            bodyToPlatform[body] = &obj;
                            relativeOffset[body] = body->position - obj.position;
                        }
                        body->position.x = obj.position.x + relativeOffset[body].x;
                        body->position.z = obj.position.z + relativeOffset[body].z;
                        body->position.y = platformAABB.max.y + body->halfExtents.y;
                        if (isPlayer) {
                            glm::vec3 inputMove(0.0f);
                            glm::vec3 front = g_camera->getForward();
                            glm::vec3 right = glm::normalize(glm::cross(front, glm::vec3(0,1,0)));
                            if (keys[GLFW_KEY_W]) inputMove += front;
                            if (keys[GLFW_KEY_S]) inputMove -= front;
                            if (keys[GLFW_KEY_A]) inputMove -= right;
                            if (keys[GLFW_KEY_D]) inputMove += right;
                            if (glm::length(inputMove) > 0.0f) {
                                inputMove = glm::normalize(inputMove);
                                float speed = (keys[GLFW_KEY_LEFT_SHIFT] || keys[GLFW_KEY_RIGHT_SHIFT]) ? 10.0f : 5.0f;
                                relativeOffset[body] += inputMove * speed * deltaTime;
                            }
                            body->velocity = platformRB->velocity;
                        } else {
                            body->velocity.x += platformRB->velocity.x;
                            body->velocity.z += platformRB->velocity.z;
                        }
                    } else {
                        if (bodyToPlatform[body] == &obj) bodyToPlatform[body] = nullptr;
                    }
                }
            }

            // Update visual positions
            for (auto& [obj, rb] : g_dynamicObjects) obj->position = rb->position;

            // Animations (doors)
            for (auto& obj : g_worldObjects) {
                if (!obj.isAnimated) continue;
                float targetRotation = obj.isOpen ? obj.openAngle : 0.0f;
                float diff = targetRotation - obj.currentRotation;
                obj.currentRotation += diff * obj.animationSpeed * deltaTime;
                if (std::fabs(diff) < 0.1f) obj.currentRotation = targetRotation;
            }
            // Trigger detection
            AABB playerAABB;
            playerAABB.min = g_player->getPosition() - glm::vec3(0.5f, 1.0f, 0.5f);
            playerAABB.max = g_player->getPosition() + glm::vec3(0.5f, 1.0f, 0.5f);
            for (auto& obj : g_worldObjects) {
                if (!obj.isTrigger) continue;
                AABB triggerAABB;
                triggerAABB.min = obj.position - obj.halfExtents;
                triggerAABB.max = obj.position + obj.halfExtents;
                if (checkAABBOverlap(playerAABB, triggerAABB)) {
                    if (!obj.triggerFired && obj.onTriggerEnter) {
                        obj.triggerFired = true;
                        obj.onTriggerEnter(*g_player);
                    }
                } else {
                    obj.triggerFired = false;
                }
            }
            // ── Damage‑Over‑Time Zones ─────────────────────────────
            playerAABB.min = g_player->getPosition() - glm::vec3(0.5f, 1.0f, 0.5f);
            playerAABB.max = g_player->getPosition() + glm::vec3(0.5f, 1.0f, 0.5f);

            for (auto& obj : g_worldObjects) {
                if (!obj.isDamageOverTime) continue;
                AABB zoneAABB;
                zoneAABB.min = obj.position - obj.halfExtents;
                zoneAABB.max = obj.position + obj.halfExtents;
                if (checkAABBOverlap(playerAABB, zoneAABB)) {
                    // Accumulate fractional damage
                    g_player->damageAccumulator += obj.damagePerSecond * deltaTime;

                    // Apply whole points
                    int damage = static_cast<int>(g_player->damageAccumulator);
                    if (damage > 0) {
                        g_player->takeDamage(damage);
                        g_player->damageAccumulator -= static_cast<float>(damage);
                        //std::cout << "Player damaged by lava! Health: " << g_player->getHealth() << std::endl;
                    }
                }
            }
            // ── Instant Death Zones ─────────────────────────────
            for (auto& obj : g_worldObjects) {
                if (!obj.isInstantKill) continue;
                AABB killAABB;
                killAABB.min = obj.position - obj.halfExtents;
                killAABB.max = obj.position + obj.halfExtents;
                if (checkAABBOverlap(playerAABB, killAABB)) {
                    g_player->takeDamage(100);   // kill outright (assuming max health = 100)
                    std::cout << "Player touched instant‑kill zone!" << std::endl;
                    break;
                }
            }
            // ── Death & Respawn ────────────────────────────────────
            if (g_player->getHealth() <= 0) {
                std::cout << "[DEATH] Health <= 0, starting respawn..." << std::endl;
                g_player->heal(100);
                std::cout << "[DEATH] Healed, health now " << g_player->getHealth() << std::endl;
                if (!g_player->getRigidBody()) {
                    std::cerr << "[DEATH] ERROR: RigidBody is null!" << std::endl;
                    std::abort();
                }
                std::cout << "[DEATH] Calling respawn..." << std::endl;
                g_levelManager.respawn(*g_player);
                std::cout << "[DEATH] Respawn complete." << std::endl;
            }
            // Fall off respawn
            if (g_player->getPosition().y < -10.0f) {
                g_levelManager.respawn(*g_player);
                std::cout << "You fell off! Respawning..." << std::endl;
            }

            g_camera->update(deltaTime);

            // View / Projection
            glm::mat4 projection = glm::perspective(glm::radians(g_camera->getFOV()),
                                                    (float)SCR_WIDTH / SCR_HEIGHT, 0.1f, 100.0f);
            glm::mat4 view = g_camera->getViewMatrix();
            Frustum frustum;
            frustum.extractPlanes(projection * view);

            g_projectionMatrix = projection;
            g_viewMatrix = view;

            // FPS & Window Title
            static FPSCounter fpsCounter;
            fpsCounter.update();
            char title[128];
            if (g_debugMode) {
                snprintf(title, sizeof(title), "OpenWorld Engine %s v%s | FPS: %.1f | Pos: (%.1f, %.1f, %.1f) [DEBUG]",
                         RELEASE_STAGE, PROJECT_VERSION, fpsCounter.getCurrentFPS(),
                         g_player->getPosition().x, g_player->getPosition().y, g_player->getPosition().z);
            } else {
                snprintf(title, sizeof(title), "OpenWorld Engine %s v%s | FPS: %.1f",
                         RELEASE_STAGE, PROJECT_VERSION, fpsCounter.getCurrentFPS());
            }
            glfwSetWindowTitle(window, title);

            // Render ground plane
            basicShader.use();
            basicShader.setMat4("projection", projection);
            basicShader.setMat4("view", view);
            glm::mat4 model = glm::mat4(1.0f);
            basicShader.setMat4("model", model);
            basicShader.setVec3("objectColor", glm::vec3(0.0f, 1.0f, 1.0f));
            if (g_groundPlane) g_groundPlane->draw();

            glm::vec3 camPos = g_camera->getPosition();
            for (auto& obj : g_worldObjects) {
                glm::vec3 min = obj.position - obj.halfExtents;
                glm::vec3 max = obj.position + obj.halfExtents;
                if (!frustum.isAABBVisible(min, max)) continue;

                float dist = glm::distance(camPos, obj.position);
                int lodLevel = 0;
                if (dist > 30.0f) lodLevel = 2;
                else if (dist > 15.0f) lodLevel = 1;

                // Choose shader for this object
                Shader* currentShader = obj.useOutlineShader ? &outlineShader : &basicShader;
                currentShader->use();

                // Set common uniforms
                currentShader->setMat4("projection", projection);
                currentShader->setMat4("view", view);

                // If it's an outline shader, set edge uniforms
                if (obj.useOutlineShader) {
                    currentShader->setVec3("edgeColor", glm::vec3(0.0f, 0.0f, 0.0f));
                    currentShader->setFloat("edgeWidth", 0.04f);
                }

                // Use the object's custom color
                currentShader->setVec3("objectColor", obj.customColor);

                // Build model matrix (same as before)
                glm::mat4 objModel = glm::mat4(1.0f);
                if (obj.isAnimated) {
                    objModel = glm::translate(objModel, obj.position + obj.hingeOffset);
                    objModel = glm::rotate(objModel, glm::radians(obj.currentRotation), obj.rotationAxis);
                    objModel = glm::translate(objModel, -obj.hingeOffset);
                    objModel = glm::scale(objModel, obj.halfExtents * 2.0f);
                } else {
                    objModel = glm::translate(objModel, obj.position);
                    if (obj.rotation != glm::vec3(0.0f)) {
                        objModel = glm::rotate(objModel, glm::radians(obj.rotation.x), glm::vec3(1,0,0));
                        objModel = glm::rotate(objModel, glm::radians(obj.rotation.y), glm::vec3(0,1,0));
                        objModel = glm::rotate(objModel, glm::radians(obj.rotation.z), glm::vec3(0,0,1));
                    }
                    if (obj.halfExtents != glm::vec3(0.5f))
                        objModel = glm::scale(objModel, obj.halfExtents * 2.0f);
                }

                currentShader->setMat4("model", objModel);
                obj.draw(lodLevel);
            }

            // Console overlay
            if (consoleOpen) {
                std::string prompt = "> " + consoleInput + (std::fmod(glfwGetTime(), 1.0) > 0.5 ? "_" : " ");
                TextRenderer::print(prompt, 10.0f, 50.0f, 1.0f, glm::vec3(1.0f));
                int linesToShow = 10;
                size_t start = (consoleHistory.size() > linesToShow) ? consoleHistory.size() - linesToShow : 0;
                for (size_t i = start; i < consoleHistory.size(); ++i) {
                    float y = 80.0f + (i - start) * 20.0f;
                    TextRenderer::print(consoleHistory[i], 10.0f, y, 1.0f, glm::vec3(0.8f));
                }
            }

            // HUD
            float healthPercent = g_player->getHealth() / 100.0f;
            float barX = 50.0f, barY = SCR_HEIGHT - 100.0f, barW = 200.0f, barH = 20.0f;
            SpriteRenderer::drawRectangle(barX, barY, barW, barH, glm::vec3(0.2f));
            SpriteRenderer::drawRectangle(barX, barY, barW * healthPercent, barH, glm::vec3(0.8f, 0.2f, 0.2f));
            float crossSize = 10.0f;
            SpriteRenderer::drawRectangle(SCR_WIDTH/2.0f - crossSize/2.0f, SCR_HEIGHT/2.0f - crossSize/2.0f,
                                          crossSize, crossSize, glm::vec3(1.0f));
            SpriteRenderer::flush();

            char healthText[32];
            snprintf(healthText, sizeof(healthText), "Health: %d", g_player->getHealth());
            TextRenderer::print(healthText, barX, barY - 30.0f, 1.5f, glm::vec3(1.0f));
            TextRenderer::printFPS(fpsCounter.getCurrentFPS(), 50.0f, SCR_HEIGHT - 1050.0f, 2.0f);

            TextRenderer::print3D("Level T", glm::vec3(-40.0f, 40.0f, -49.9f),   // position
                                  glm::vec3(180.0f, 0.0f, 0.0f),               // rotation
                                  2.0f,                                       // scale
                                  glm::vec3(1.0f, 1.0f, 1.0f));            // color text

            // Draw 3D labels (checkpoints, signs, etc.)
            if (shader3D && g_camera) {   // <-- safety check around whole block
                for (auto& obj : g_worldObjects) {
                    if (obj.label.empty()) continue;
                    // … rest of the label code as before …
                }
            }

            // Draw 3D labels (checkpoints, signs, etc.)
            for (auto& obj : g_worldObjects) {
               if (obj.label.empty()) continue;

                // Check frustum culling to avoid drawing labels behind the camera
                glm::vec3 min = obj.position - obj.halfExtents;
                glm::vec3 max = obj.position + obj.halfExtents;
                if (!frustum.isAABBVisible(min, max)) continue;

                 // Position label above the object
                glm::vec3 labelPos = obj.position + glm::vec3(0.0f, obj.halfExtents.y + 0.3f, 0.0f);

                // Billboard: rotate label to face the camera
                glm::vec3 labelToCam = glm::normalize(camPos - labelPos);
                float yaw = glm::degrees(atan2(labelToCam.x, labelToCam.z));
                glm::vec3 billboardRotation = glm::vec3(0.0f, yaw, 0.0f);

                // Optionally color by state (green if unlocked, otherwise white)
                glm::vec3 labelColor = glm::vec3(1.0f);
                if (obj.isTrigger && LevelManager::getInstance().isCheckpointUnlocked(obj.label)) {
                    labelColor = glm::vec3(0.2f, 1.0f, 0.2f); // green for unlocked
                }

                // Scale small so it's readable but not huge
                float labelScale = 0.15f;

                // Render using the 3D text system
                TextRenderer::print3D(obj.label, labelPos, billboardRotation, labelScale, labelColor);
            }

            // Debug wireframes
            if (g_debugMode) {
                basicShader.use();
                basicShader.setMat4("projection", projection);
                basicShader.setMat4("view", view);

                for (const auto& aabb : g_physics.getStaticAABBs()) {
                    glm::mat4 dbgModel = glm::translate(glm::mat4(1.0f), (aabb.min + aabb.max) * 0.5f);
                    dbgModel = glm::scale(dbgModel, (aabb.max - aabb.min));
                    basicShader.setMat4("model", dbgModel);
                    basicShader.setVec3("objectColor", glm::vec3(0,1,0));
                    glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
                    Cube::generateHighPoly(0.5f).draw();
                    glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
                }

                for (const auto& oc : g_physics.getOrientedColliders()) {
                    glm::mat4 dbgModel = glm::translate(glm::mat4(1.0f), oc.position);
                    dbgModel = dbgModel * glm::mat4(oc.rotation);
                    dbgModel = glm::scale(dbgModel, oc.halfExtents * 2.0f);
                    basicShader.setMat4("model", dbgModel);
                    basicShader.setVec3("objectColor", glm::vec3(0,0,1));
                    glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
                    Cube::generateHighPoly(0.5f).draw();
                    glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
                }

                for (const auto* body : g_physics.getBodies()) {
                    glm::mat4 dbgModel = glm::translate(glm::mat4(1.0f), body->position);
                    dbgModel = glm::scale(dbgModel, body->halfExtents * 2.0f);
                    basicShader.setMat4("model", dbgModel);
                    basicShader.setVec3("objectColor", glm::vec3(1,1,0));
                    glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
                    Cube::generateHighPoly(0.5f).draw();
                    glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
                }
            }

            glfwSwapBuffers(window);
        }
    }

    // Cleanup
    if (appState == AppState::GAME) cleanupGame(window);
    TextRenderer::shutdown();
    SpriteRenderer::shutdown();
    glfwTerminate();
    return 0;
}